package com.xue.cookbook.auth.dao;

import com.xue.cookbook.auth.model.AuthPermissions;
import java.util.List;

public interface AuthPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permissions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permissions
     *
     * @mbg.generated
     */
    int insert(AuthPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permissions
     *
     * @mbg.generated
     */
    AuthPermissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permissions
     *
     * @mbg.generated
     */
    List<AuthPermissions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permissions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthPermissions record);
}