package com.xue.cookbook.auth.dao;

import com.xue.cookbook.auth.model.AuthRolePermissionsRel;
import java.util.List;

public interface AuthRolePermissionsRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permissions_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permissions_rel
     *
     * @mbg.generated
     */
    int insert(AuthRolePermissionsRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permissions_rel
     *
     * @mbg.generated
     */
    AuthRolePermissionsRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permissions_rel
     *
     * @mbg.generated
     */
    List<AuthRolePermissionsRel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_role_permissions_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthRolePermissionsRel record);
}