package com.xue.cookbook.recipes.dao;

import com.xue.cookbook.recipes.model.MaterialNutritionType;
import java.util.List;

public interface MaterialNutritionTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition_type
     *
     * @mbg.generated
     */
    int insert(MaterialNutritionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition_type
     *
     * @mbg.generated
     */
    MaterialNutritionType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition_type
     *
     * @mbg.generated
     */
    List<MaterialNutritionType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialNutritionType record);
}