package com.xue.cookbook.recipes.dao;

import com.xue.cookbook.recipes.model.MaterialCategory;
import java.util.List;

public interface MaterialCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_category
     *
     * @mbg.generated
     */
    int insert(MaterialCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_category
     *
     * @mbg.generated
     */
    MaterialCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_category
     *
     * @mbg.generated
     */
    List<MaterialCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialCategory record);


    List<MaterialCategory> selectAllActive();
}