package com.xue.cookbook.recipes.dao;

import com.xue.cookbook.recipes.model.MaterialNutrition;
import java.util.List;

public interface MaterialNutritionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition
     *
     * @mbg.generated
     */
    int insert(MaterialNutrition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition
     *
     * @mbg.generated
     */
    MaterialNutrition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition
     *
     * @mbg.generated
     */
    List<MaterialNutrition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_nutrition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialNutrition record);
}