package com.xue.cookbook.recipes.dao;

import com.xue.cookbook.recipes.model.RecipesMenu;
import java.util.List;

public interface RecipesMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes_menu
     *
     * @mbg.generated
     */
    int insert(RecipesMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes_menu
     *
     * @mbg.generated
     */
    RecipesMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes_menu
     *
     * @mbg.generated
     */
    List<RecipesMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RecipesMenu record);
}